apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    app_version: "{{ .Chart.AppVersion }}"
    chart: {{ template "app.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: "{{ .Values.service.type }}"
  ports:
  {{- range $name, $def := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $def.port }}
      targetPort: {{ $def.targetPort }}
  {{- end }}
  selector:
    app: {{ template "app.name" . }}
    release: "{{ .Release.Name }}"
